//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Kadro : global::System.Configuration.ApplicationSettingsBase {
        
        private static Kadro defaultInstance = ((Kadro)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Kadro())));
        
        public static Kadro Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu1 {
            get {
                return ((string)(this["Oyuncu1"]));
            }
            set {
                this["Oyuncu1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu2 {
            get {
                return ((string)(this["Oyuncu2"]));
            }
            set {
                this["Oyuncu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu3 {
            get {
                return ((string)(this["Oyuncu3"]));
            }
            set {
                this["Oyuncu3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu4 {
            get {
                return ((string)(this["Oyuncu4"]));
            }
            set {
                this["Oyuncu4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu5 {
            get {
                return ((string)(this["Oyuncu5"]));
            }
            set {
                this["Oyuncu5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu6 {
            get {
                return ((string)(this["Oyuncu6"]));
            }
            set {
                this["Oyuncu6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu7 {
            get {
                return ((string)(this["Oyuncu7"]));
            }
            set {
                this["Oyuncu7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu8 {
            get {
                return ((string)(this["Oyuncu8"]));
            }
            set {
                this["Oyuncu8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu9 {
            get {
                return ((string)(this["Oyuncu9"]));
            }
            set {
                this["Oyuncu9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu10 {
            get {
                return ((string)(this["Oyuncu10"]));
            }
            set {
                this["Oyuncu10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu11 {
            get {
                return ((string)(this["Oyuncu11"]));
            }
            set {
                this["Oyuncu11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu12 {
            get {
                return ((string)(this["Oyuncu12"]));
            }
            set {
                this["Oyuncu12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu13 {
            get {
                return ((string)(this["Oyuncu13"]));
            }
            set {
                this["Oyuncu13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu14 {
            get {
                return ((string)(this["Oyuncu14"]));
            }
            set {
                this["Oyuncu14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu15 {
            get {
                return ((string)(this["Oyuncu15"]));
            }
            set {
                this["Oyuncu15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu16 {
            get {
                return ((string)(this["Oyuncu16"]));
            }
            set {
                this["Oyuncu16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu17 {
            get {
                return ((string)(this["Oyuncu17"]));
            }
            set {
                this["Oyuncu17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Oyuncu18 {
            get {
                return ((string)(this["Oyuncu18"]));
            }
            set {
                this["Oyuncu18"] = value;
            }
        }
    }
}
